### ISSUE TITLE
Error In Installation

### ISSUE THREAD

**Issue by zaintech01** [quantumcore/paradoxiaRAT#17]
zain-hundal  zain  ~  Documents  paradoxiaRAT  master  ✎  $  sudo python3 paradoxia.py
Traceback (most recent call last):
  File "/home/zain-hundal/Documents/paradoxiaRAT/paradoxia.py", line 10, in <module>
    from kernel.main import *
  File "/home/zain-hundal/Documents/paradoxiaRAT/kernel/main.py", line 22, in <module>
    from .other import *
  File "/home/zain-hundal/Documents/paradoxiaRAT/kernel/other.py", line 1, in <module>
    from plyer import notification
ModuleNotFoundError: No module named 'plyer'

**Comment by quantumcore** [comment]
```
python3 -m pip install plyer
```

:)

**Comment by jhorvitz124** [comment]
I have a similar issue, but instead of plyer it is PIL

**Comment by Lopastudio** [comment]
same with PIL

**Comment by quantumcore** [comment]
Try: `python3 -m pip install Pillow`
